---
title: "Wild Git Collaboration Practice"
format: 
  html:
    code-fold: show
execute: 
  warning: false
  message: false
---


## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)

library(tidyverse)

data("diamonds")

p_v_carat <- ggplot(data=diamonds,aes(x=carat,y=price))+
  geom_jitter()
p_v_carat

```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

diamond_subset <- diamonds |> filter(cut=="Ideal")

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
diamond_break_isa <- diamond_subset |>
  mutate(broke = 'I am broken')

```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

